name: Scheduled workflow

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  rebuild_staging_5_minute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install and Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site (staging)
        run: hugo --enableGitInfo --minify --gc --logLevel info --baseURL https://monal-im.github.io/monal-im.org/site/

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/staging'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: site
          keep_files: false

  rebuild_master_5_minute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install and Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build site (master)
        run: hugo --enableGitInfo --minify --gc --logLevel info --baseURL https://monal-im.org/
      
      - name: Create tar archive
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "public" \
            -cvf "$RUNNER_TEMP/master_public.tar" \
            --exclude=.git \
            --exclude=.github \
            .
      - name: Upload tar archive to github pages
        run: |
          git config --local user.email "pushBot@monal-im.org"
          git config --local user.name "Monal-IM-Push[BOT]"
          git reset --hard
          git checkout gh-pages
          cp "$RUNNER_TEMP/master_public.tar" "master_public.tar"
          git add master_public.tar
          git commit -m "Add new master_public.tar"
          git push
